# set the name ov venv directory
VENV := venv

# this is the default target, when make executed without arguments
all: venv

$(VENV)/bin/active: requirements.txt
        python3 -m venv $(VENV)
        ./$(VENV)/bin/pip install -r requirements.txt

# venv is a shortcut target
venv: $(VENV)/bin/active

run: venv
     ./$(VENV)/bin/python3 app.py

clean:
    rm -rf $(VENV)
    find . -type f -name '*.pyc' -delete

.PHONY: all venv run clean
